### PR TITLE
Add coffee dataset

### PR DESCRIPTION
**Pull request by Robinlovelace**
This is a dataset from https://github.com/Robinlovelace/geocompr/pull/145 that has been further cleaned and tidied. It's now tiny, containing only 47 rows. It's a good example because not all the country names are standard - so care needs to be taken when joining to datasets of countries.

### CODE REVIEW

**Comment by Nowosad** [comment]
Hey @Robinlovelace - I've opened the http://rpubs.com/RobinLovelace/352549 site and I think that there is one problem with this visualization. There are several countries having value of 0. On the map, they have the same color as those with values up to 500. I think it is confusing. How to solve this issue? Depends.. if NA means - no export, then NA should be joined with 0 in one color category. If NA means - no data, then there should be NA category, 0 category, and more than 0 categories.

**Comment by Nowosad** [comment]
Update: Quote from the pdf "A figure of 0 in the table can mean a volume of less than 500 bags, due to rounding.". Therefore, I think the color legend should be: No data (or zero, depends), less than 500 bags, 1000 - ...., etc.

**Comment by Robinlovelace** [comment]
Agreed - that is a good fix, will do. Would it also be worth changing the potentially confusing column titles, currently `y16` and `y17`: `coffee_production_2016` and `coffee_production_2017` would probably be better. One of the main advantages of this datasets over others such as the one from the World Bank is its simplicity so I was also considering having only one coffee production variable. It says in the documentation that this dataset is for teaching not research: I do not regard it as a particularly accurate or scientific dataset but it certainly provides an interesting overview of a product that many programmers seem to be dependent on.

**Comment by Nowosad** [comment]
I like that the data came from pdf. This workflow could be really helpful in many cases.
Let me know when you fixed the data here and the visualization in the book repo and I'll merge this pull request.

**Comment by Robinlovelace** [comment]
Update - this creates `NA`s but see now it's better to show the uncertainty in the legend not in the data - will update:

```r
#' coffee_data = slice(d, -c(1:9)) %>% 
#'         select(name_long = 1, coffee_production_2016 = 2, coffee_production_2017 = 3) %>% 
#'         filter(!is.na(coffee_production_2016)) %>% 
#'         mutate_at(2:3, str_replace, " ", "") %>% 
#'         mutate_at(2:3, as.integer) %>% 
#'         mutate_if(is.numeric, na_if, 0)
```

**Comment by Robinlovelace** [comment]
Latest version prints like this - the next commit should make this good to merge I think: 

image

**Comment by Robinlovelace** [comment]
Note in the data it's still 0 - that's fine I think because that's the data that we were given. It's the interpretation of that data that's important and something we should comment on in c3 when we use this. And the fact than not all countries will join and how to identify them = important to demonstrate.

**Comment by Nowosad** [comment]
@Robinlovelace - thanks. I've updated the documentation and submit the new version to CRAN.

**Pull request merged**
