### PR TITLE
restore missing weights files

### PR DESCRIPTION
**Pull request by rsbivand**
Trying to  fix https://github.com/Nowosad/spData/issues/47, but needs your attention as serialization imposes R >= 3.5.0

### CODE REVIEW

**Comment by Nowosad** [comment]
@rsbivand Roger, what do you think about saving the data with `version = 2`?

**Comment by rsbivand** [comment]
That makes sense, and removes more invasive changes. Was the omission of the weights files an oversight when rebuilding the CRS, or planned?

**Comment by Nowosad** [comment]
Omission of the weights files was definitely an oversight.

**Comment by rsbivand** [comment]
Please let me know if this works better, and that I didn't inadvertently substitute the old sp objects.

**Pull request merged**
