### PR TITLE
Specify minimum sf version

### PR DESCRIPTION
**Pull request by Robinlovelace**
For https://github.com/Nowosad/spData/issues/43

### CODE REVIEW

**Comment by Nowosad** [comment]
@Robinlovelace you probably should add `>=`. I would also suggest using version `0.9-1` as it fixes some bugs.

**Comment by Robinlovelace** [comment]
Thanks @Nowosad, missed that!

**Comment by Nowosad** [comment]
Thanks @Robinlovelace - I have updated it with another changes - https://github.com/Nowosad/spData/commit/29cc208e00b01e09670212d8749511c7e7113926

**Comment by Robinlovelace** [comment]
:+1:

**Pull request closed without merging**
