### PR TITLE
Update world data

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Nowosad** [comment]
@Robinlovelace can you create a simple reprex with your system info? I do not want to update this object, if the `aggregate` issue is not related to it...
This is my reprex:

``` r
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 7.0.0
library(spData)
world_agg2 = aggregate(world["pop"], by = list(world$continent),
                       FUN = sum, na.rm = TRUE)  
class(world_agg2)
#> [1] "sf"         "data.frame"
```

<sup>Created on 2020-03-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                          
#>  version  R version 3.6.3 (2020-02-29)   
#>  os       Fedora 31 (Workstation Edition)
#>  system   x86_64, linux-gnu              
#>  ui       X11                            
#>  language (EN)                           
#>  collate  en_US.UTF-8                    
#>  ctype    en_US.UTF-8                    
#>  tz       Europe/Warsaw                  
#>  date     2020-03-26                     
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version    date       lib source                              
#>  assertthat    0.2.1      2019-03-21 [1] CRAN (R 3.6.0)                      
#>  backports     1.1.5      2019-10-02 [1] CRAN (R 3.6.1)                      
#>  callr         3.4.2      2020-02-12 [1] CRAN (R 3.6.3)                      
#>  class         7.3-15     2019-01-01 [2] CRAN (R 3.6.3)                      
#>  classInt      0.4-2      2019-10-17 [1] CRAN (R 3.6.1)                      
#>  cli           2.0.2      2020-02-28 [1] CRAN (R 3.6.2)                      
#>  codetools     0.2-16     2018-12-24 [2] CRAN (R 3.6.3)                      
#>  crayon        1.3.4      2017-09-16 [1] CRAN (R 3.6.0)                      
#>  DBI           1.1.0      2019-12-15 [1] CRAN (R 3.6.2)                      
#>  desc          1.2.0      2018-05-01 [1] CRAN (R 3.6.0)                      
#>  devtools      2.2.2      2020-02-17 [1] CRAN (R 3.6.3)                      
#>  digest        0.6.25     2020-02-23 [1] CRAN (R 3.6.2)                      
#>  e1071         1.7-3      2019-11-26 [1] CRAN (R 3.6.1)                      
#>  ellipsis      0.3.0      2019-09-20 [1] CRAN (R 3.6.1)                      
#>  evaluate      0.14       2019-05-28 [1] CRAN (R 3.6.0)                      
#>  fansi         0.4.1      2020-01-08 [1] CRAN (R 3.6.2)                      
#>  fs            1.3.2      2020-03-05 [1] CRAN (R 3.6.2)                      
#>  glue          1.3.2      2020-03-12 [1] CRAN (R 3.6.3)                      
#>  highr         0.8        2019-03-20 [1] CRAN (R 3.6.0)                      
#>  htmltools     0.4.0      2019-10-04 [1] CRAN (R 3.6.1)                      
#>  KernSmooth    2.23-16    2019-10-15 [2] CRAN (R 3.6.3)                      
#>  knitr         1.28       2020-02-06 [1] CRAN (R 3.6.2)                      
#>  lattice       0.20-38    2018-11-04 [2] CRAN (R 3.6.3)                      
#>  magrittr      1.5        2014-11-22 [1] CRAN (R 3.6.0)                      
#>  memoise       1.1.0      2017-04-21 [1] CRAN (R 3.6.0)                      
#>  pkgbuild      1.0.6      2019-10-09 [1] CRAN (R 3.6.1)                      
#>  pkgload       1.0.2      2018-10-29 [1] CRAN (R 3.6.0)                      
#>  prettyunits   1.1.1      2020-01-24 [1] CRAN (R 3.6.2)                      
#>  processx      3.4.2      2020-02-09 [1] CRAN (R 3.6.3)                      
#>  ps            1.3.2      2020-02-13 [1] CRAN (R 3.6.2)                      
#>  R6            2.4.1      2019-11-12 [1] CRAN (R 3.6.1)                      
#>  raster        3.0-12     2020-01-30 [1] CRAN (R 3.6.3)                      
#>  Rcpp          1.0.4      2020-03-17 [1] CRAN (R 3.6.3)                      
#>  remotes       2.1.1      2020-02-15 [1] CRAN (R 3.6.2)                      
#>  rlang         0.4.5.9000 2020-03-20 [1] Github (r-lib/rlang@a90b04b)        
#>  rmarkdown     2.1        2020-01-20 [1] CRAN (R 3.6.2)                      
#>  rprojroot     1.3-2      2018-01-03 [1] CRAN (R 3.6.0)                      
#>  sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 3.6.0)                      
#>  sf          * 0.9-0      2020-03-25 [1] Github (r-spatial/sf@5187565)       
#>  sp            1.4-1      2020-02-28 [1] CRAN (R 3.6.3)                      
#>  spData      * 0.3.3      2020-02-10 [1] local                               
#>  spDataLarge   0.3.1      2020-01-19 [1] Github (nowosad/spDataLarge@1f52612)
#>  stringi       1.4.6      2020-02-17 [1] CRAN (R 3.6.2)                      
#>  stringr       1.4.0      2019-02-10 [1] CRAN (R 3.6.1)                      
#>  testthat      2.3.2      2020-03-02 [1] CRAN (R 3.6.3)                      
#>  units         0.6-6      2020-03-16 [1] CRAN (R 3.6.3)                      
#>  usethis       1.5.1      2019-07-04 [1] CRAN (R 3.6.0)                      
#>  withr         2.1.2      2018-03-15 [1] CRAN (R 3.6.0)                      
#>  xfun          0.12       2020-01-13 [1] CRAN (R 3.6.2)                      
#>  yaml          2.2.1      2020-02-01 [1] CRAN (R 3.6.2)                      
#> 
#> [1] /home/jn/R/x86_64-redhat-linux-gnu-library/3.6
#> [2] /usr/lib64/R/library
#> [3] /usr/share/R/library
```

</details>

**Comment by Robinlovelace** [comment]
``` r
remotes::install_github("nowosad/spData")
#> Using github PAT from envvar GITHUB_PAT
#> Skipping install of 'spData' from a github remote, the SHA1 (ea4c31e0) has not changed since last install.
#>   Use `force = TRUE` to force installation
    library(spData)
    world_agg2 = aggregate(world["pop"], by = list(world$continent),
                           FUN = sum, na.rm = TRUE)  
    class(world_agg2)
#> [1] "data.frame"
```

<sup>Created on 2020-03-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 3.6.3 (2020-02-29)
#>  os       Ubuntu 18.04.4 LTS          
#>  system   x86_64, linux-gnu           
#>  ui       X11                         
#>  language en_GB:en                    
#>  collate  en_GB.UTF-8                 
#>  ctype    en_GB.UTF-8                 
#>  tz       Europe/London               
#>  date     2020-03-26                  
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version    date       lib source                              
#>  assertthat    0.2.1      2019-03-21 [2] CRAN (R 3.6.0)                      
#>  backports     1.1.5      2019-10-02 [1] CRAN (R 3.6.1)                      
#>  callr         3.4.2      2020-02-12 [1] CRAN (R 3.6.2)                      
#>  cli           2.0.2      2020-02-28 [1] CRAN (R 3.6.2)                      
#>  codetools     0.2-16     2018-12-24 [4] CRAN (R 3.5.2)                      
#>  crayon        1.3.4      2017-09-16 [2] standard (@1.3.4)                   
#>  curl          4.3        2019-12-02 [2] CRAN (R 3.6.2)                      
#>  desc          1.2.0      2018-05-01 [2] standard (@1.2.0)                   
#>  devtools      2.2.2      2020-02-17 [1] CRAN (R 3.6.2)                      
#>  digest        0.6.25     2020-02-23 [1] CRAN (R 3.6.2)                      
#>  ellipsis      0.3.0      2019-09-20 [3] CRAN (R 3.6.1)                      
#>  evaluate      0.14       2019-05-28 [2] CRAN (R 3.6.0)                      
#>  fansi         0.4.1      2020-01-08 [1] CRAN (R 3.6.2)                      
#>  fs            1.3.2      2020-03-05 [2] CRAN (R 3.6.3)                      
#>  glue          1.3.2      2020-03-12 [2] CRAN (R 3.6.3)                      
#>  highr         0.8        2019-03-20 [3] CRAN (R 3.5.3)                      
#>  htmltools     0.4.0.9003 2020-03-25 [1] Github (rstudio/htmltools@1a35072)  
#>  knitr         1.28       2020-02-06 [1] CRAN (R 3.6.2)                      
#>  lattice       0.20-40    2020-02-19 [2] CRAN (R 3.6.2)                      
#>  magrittr      1.5        2014-11-22 [2] CRAN (R 3.5.2)                      
#>  memoise       1.1.0      2017-04-21 [3] CRAN (R 3.5.0)                      
#>  pkgbuild      1.0.6      2019-10-09 [2] CRAN (R 3.6.1)                      
#>  pkgload       1.0.2      2018-10-29 [3] CRAN (R 3.5.1)                      
#>  prettyunits   1.1.1      2020-01-24 [1] CRAN (R 3.6.2)                      
#>  processx      3.4.2      2020-02-09 [2] CRAN (R 3.6.2)                      
#>  ps            1.3.2      2020-02-13 [1] CRAN (R 3.6.3)                      
#>  R6            2.4.1      2019-11-12 [2] CRAN (R 3.6.1)                      
#>  raster        3.0-12     2020-01-30 [1] CRAN (R 3.6.2)                      
#>  Rcpp          1.0.4      2020-03-17 [1] CRAN (R 3.6.3)                      
#>  remotes       2.1.1      2020-02-15 [1] CRAN (R 3.6.2)                      
#>  rlang         0.4.5.9000 2020-03-25 [1] Github (r-lib/rlang@a90b04b)        
#>  rmarkdown     2.1.1      2020-03-25 [1] Github (rstudio/rmarkdown@947b872)  
#>  rprojroot     1.3-2      2018-01-03 [2] CRAN (R 3.5.3)                      
#>  sessioninfo   1.1.1      2018-11-05 [3] CRAN (R 3.5.1)                      
#>  sp            1.4-1      2020-02-28 [1] CRAN (R 3.6.2)                      
#>  spData      * 0.3.3      2020-03-26 [1] Github (nowosad/spData@ea4c31e)     
#>  spDataLarge   0.3.1      2020-01-12 [1] Github (nowosad/spDataLarge@1f52612)
#>  stringi       1.4.6      2020-02-17 [1] CRAN (R 3.6.2)                      
#>  stringr       1.4.0      2019-02-10 [2] standard (@1.4.0)                   
#>  testthat      2.3.2      2020-03-02 [1] CRAN (R 3.6.3)                      
#>  usethis       1.5.1.9000 2020-03-25 [1] Github (r-lib/usethis@337d1a3)      
#>  withr         2.1.2      2018-03-15 [2] CRAN (R 3.5.3)                      
#>  xfun          0.12       2020-01-13 [1] CRAN (R 3.6.2)                      
#>  yaml          2.2.1      2020-02-01 [1] CRAN (R 3.6.2)                      
#> 
#> [1] /home/robin/R/x86_64-pc-linux-gnu-library/3.6
#> [2] /usr/local/lib/R/site-library
#> [3] /usr/lib/R/site-library
#> [4] /usr/lib/R/library
```

</details>

**Comment by Robinlovelace** [comment]
Interestingly that new PR does not fix it:

``` r
remotes::install_github("nowosad/spData", ref = "update-world")
#> Using github PAT from envvar GITHUB_PAT
#> Skipping install of 'spData' from a github remote, the SHA1 (95c2e270) has not changed since last install.
#>   Use `force = TRUE` to force installation
library(spData)
world_agg2 = aggregate(world["pop"], by = list(world$continent),
                       FUN = sum, na.rm = TRUE)  
class(world_agg2)
#> [1] "data.frame"
```

<sup>Created on 2020-03-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Nowosad** [comment]
@Robinlovelace you do not have sf attached...

**Comment by Robinlovelace** [comment]
Update with sf on PR version:

``` r
remotes::install_github("nowosad/spData", ref = "update-world")
#> Using github PAT from envvar GITHUB_PAT
#> Skipping install of 'spData' from a github remote, the SHA1 (95c2e270) has not changed since last install.
#>   Use `force = TRUE` to force installation
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 7.0.0
library(spData)
world_agg2 = aggregate(world["pop"], by = list(world$continent),
                       FUN = sum, na.rm = TRUE)  
class(world_agg2)
#> [1] "sf"         "data.frame"
```

<sup>Created on 2020-03-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Robinlovelace** [comment]
I do not get the issue on released version of sf and spData:

``` r
remotes::install_github("nowosad/spData")
#> Using github PAT from envvar GITHUB_PAT
#> Skipping install of 'spData' from a github remote, the SHA1 (ea4c31e0) has not changed since last install.
#>   Use `force = TRUE` to force installation
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 7.0.0
library(spData)
world_agg2 = aggregate(world["pop"], by = list(world$continent),
                       FUN = sum, na.rm = TRUE)  
class(world_agg2)
#> [1] "sf"         "data.frame"
```

<sup>Created on 2020-03-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Nowosad** [comment]
Closing for now.

**Pull request closed without merging**
