### PR TITLE
checking data compatibility re: spdep

### PR DESCRIPTION
**Pull request by rsbivand**
These changes clean some datasets, permit spdep to hand off data storage to spData, and provide the basis for the sf/spdep nb_sf vignette about constructing neighbours. Once this reaches CRAN, (check version numbers), I'll be able to start releasing spdep, start transiting spdep to github/r-spatial, and warning downstream package maintainers who expect datasets to be carried by spdep (there may be a lot). Have used roxygen2::roxygenize("spData") to regenerate man/ etc.

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Great stuff - I noticed the `afcon` dataset was present in both pkgs so really happy to see this: will prevent confusion and duplicate datasets.

**Comment by Nowosad** [comment]
I'm going to clean spData a little bit and submit to CRAN today.

**Comment by Robinlovelace** [comment]
Great - will allow us to delete this line when it goes on cran: https://github.com/Robinlovelace/geocompr/blame/rev1/04-spatial-operations.Rmd#L507

**Comment by rsbivand** [comment]
Thanks. I'll start reverse dependency checking spdep to find CRAN packages using spdep data() that should move to spData (and shapes/weights).

**Comment by rsbivand** [comment]
Reverse dependency checking completed and affected package maintainers warned.

**Pull request merged**
