### PR TITLE
Add congruent and 2 related datasets for teaching

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Please take a look @Nowosad - think most things are in there but sure I've missed something. Other than updating the README is there anything else I should do?

**Comment by Nowosad** [comment]
**pkgdown**

**Comment by Robinlovelace** [comment]
Job done.

**Comment by Robinlovelace** [comment]
OK the hole is gone now: 
image

**Comment by Robinlovelace** [comment]
Good to go I think. I've updated the plotting example and fixed the issue with the 'whole'. I've not got the latest version of **roxygen2** and want to stick with the CRAN version so not updated the documentation.

**Pull request merged**
