### PR TITLE
remove ESRI Shapefile

### PR DESCRIPTION
**Pull request by rsbivand**
Further to #62

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Looks good to me.

**Review by Robinlovelace — APPROVED** [review]

**Comment by Nowosad** [comment]
Thanks @rsbivand -- should I submit it to CRAN soon or should I wait a week or two?

**Comment by rsbivand** [comment]
Maybe wait for `spdep`, `spatialreg` and `sphet` to complete? See https://github.com/Nowosad/spData/issues/62#issuecomment-2510229276, @gpiras said he hopes to submit this week, I'll try to submit today.

**Comment by gpiras** [comment]
@rsbivand  sphet is not. I was checking the package on my mac and everything was fine so I submitted. However, the checks fail in Windows and Debian (see mail below). I will try later to fix the problem with Ubuntu, but I don't have  windows so this might take longer than expected.  

Dear maintainer,

package sphet_2.1.tar.gz does not pass the incoming checks automatically, please see the following pre-tests (additional issue checks):
Windows: <https://win-builder.r-project.org/incoming_pretest/sphet_2.1_20241205_174314/Windows/00check.log>
Status: 1 NOTE
Debian: <https://win-builder.r-project.org/incoming_pretest/sphet_2.1_20241205_174314/Debian/00check.log>
Status: 1 NOTE

**Comment by rsbivand** [comment]
The default version of HTML tidy is from 2006 on macOS https://stat.ethz.ch/pipermail/r-sig-mac/2022-May/014443.html. If you can install an updated version, that will help. Is the github repo up-to-date? I can pull and check if that helps.

**Comment by gpiras** [comment]
I have installed version 5.8.0 (https://github.com/htacg/tidy-html5/releases/download/5.8.0/tidy-5.8.0-macos-x86_64+arm64.dmg), but no help. github is up-to-date now. Sure if you could do that it would be great!

**Comment by rsbivand** [comment]
Did you push the version you submitted to CRAN to the github repo?

**Comment by gpiras** [comment]
yes. built and check with no problems on mac.

**Comment by rsbivand** [comment]
@gpiras Created https://github.com/gpiras/sphet/pull/22, hope it helps; I don't see the NOTE.

**Comment by rsbivand** [comment]
I've emailed the GWnnegPCA maintainer at a university email and hope that helps.

**Comment by rsbivand** [comment]
`sphet` on CRAN, thanks @gpiras

**Pull request merged**
