### PR TITLE
Start on #64

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Nowosad** [comment]
@Robinlovelace are you sure that you updated the world object? This is what I see in this branch:

```
library(sf)
library(spData)
world
mapview::mapview(world)
```

**Comment by Robinlovelace** [comment]
> @Robinlovelace are you sure that you updated the world object? This is what I see in this branch:
> 
> ```
> library(sf)
> library(spData)
> world
> mapview::mapview(world)
> ```
> 
> 

Will check and get back..

**Comment by Robinlovelace** [comment]
Update after latest commit with Russia...

image

**Comment by Robinlovelace** [comment]
Ukraine...

image

**Comment by Robinlovelace** [comment]
Updated and ready for review again @Nowosad . No manual edits this time.

**Comment by Nowosad** [comment]
Neat! Thansk

**Pull request merged**
